name: Docker Image builder

on:
  push:
    paths:
    - '**builder/Dockerfile'
    - '**builder.yml'

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Docker Image builder
      run: |
        echo $PACKAGE_TOCKEN | docker login --username soerensofke --password-stdin
        docker build -t docker.pkg.github.com/soerensofke/diamonddust/builder:latest ./.github/workflows/builder
        docker push docker.pkg.github.com/soerensofke/diamonddust/builder:latest
      env:
          PACKAGE_TOCKEN: ${{ secrets.PACKAGE_TOCKEN }}
