name: CI in Docker

on: [push]

jobs:
  myjob:
    runs-on: ubuntu-18.04
    container:
      image: soerensofke/diamonddust:verilog
    steps:
    - uses: actions/checkout@v1
    - run: make build
    - run: make compile
    - run: make simulate
    - run: make synthesize
    - run: make resources
    - run: make clean    
