name: CI in Docker

on: [push]

jobs:
  myjob:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - uses: docker://soerensofke/diamondust:verilog
    - run: |
        echo $HOME
        ls $HOME
        echo 'int main(void) { return 0; }' > hello.c && riscv32-unknown-elf-gcc -o hello hello.c
        
