@startuml Dockerfile dependencies
skinparam componentStyle uml2
skinparam handwritten true
skinparam monochrome true
skinparam defaultFontName DejaVu

frame "Dependencies" {

    artifact "iStyle  " as iStyle {
        component "iStyle" as iStyleBinary
    }

    artifact "riscv-gnu-toolchain-rv32i   " as riscvGnuToolchainRv32i {
        component "riscv32-unknown-elf-*" as riscv32Binary
    }

    file "ubuntu:18.04" as ubuntu
    file builder
    file verilog
    file scratch

    builder ..> ubuntu
    iStyle ..> builder
    iStyle ..> scratch
    riscvGnuToolchainRv32i ..> builder
    riscvGnuToolchainRv32i ..> scratch
    verilog ..> ubuntu
    verilog *-- riscv32Binary
    verilog *-- iStyleBinary
}
@enduml
