name: Docker Image CI

on:
  push:
    paths:
    - '**Dockerfile'
    - '**dockerimage.yml'

jobs:

  build:
 
    runs-on: ubuntu-18.04
 
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image for Gitpod
      run: 
        docker build -t soerensofke/diamonddust:gitpod .
        docker push soerensofke/diamonddust:gitpod
