name: CI on ice40up5k

on: [push]

jobs:
  myjob:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v1
    - run: sudo date -s "$(wget -qSO- --max-redirect=0 google.com 2>&1 | grep Date: | cut -d' ' -f5-8)Z"
