name: Docker Image iStyle

on:
  push:
    paths:
    - '**iStyle/Dockerfile'
    - '**iStyle.yml'

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Docker Image iStyle
      run: |
        echo $PACKAGE_TOKEN | docker login docker.pkg.github.com --username soerensofke --password-stdin
        docker build -t docker.pkg.github.com/soerensofke/diamonddust/istyle:latest ./.github/workflows/iStyle
        docker push docker.pkg.github.com/soerensofke/diamonddust/istyle:latest
      env:
          PACKAGE_TOKEN: ${{ secrets.PACKAGE_TOKEN }}
