name: Docker Image riscv-gnu-toolchain-rv32i

on:
  push:
    paths:
    - '**riscv-gnu-toolchain-rv32i/Dockerfile'
    - '**riscv-gnu-toolchain-rv32i.yml'

jobs:

  build:
 
    runs-on: ubuntu-18.04
 
    steps:
    - uses: actions/checkout@v1
    - name: Docker Image riscv-gnu-toolchain-rv32i
      run: |
        echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin        
        docker build -t soerensofke/diamonddust:riscvGnuToolchainRv32i ./.github/workflows/riscv-gnu-toolchain-rv32i
        docker push soerensofke/diamonddust:riscvGnuToolchainRv32i        
      env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
