name: Docker Image riscv-gnu-toolchain-rv32i

on:
  push:
    paths:
    - '**riscv-gnu-toolchain-rv32i/Dockerfile'
    - '**riscv-gnu-toolchain-rv32i.yml'

jobs:

  build:
 
    runs-on: ubuntu-18.04
 
    steps:
    - uses: actions/checkout@v1
    - name: Docker Image riscv-gnu-toolchain-rv32i
      run: |
        echo $PACKAGE_TOKEN | docker login docker.pkg.github.com --username soerensofke --password-stdin    
        docker build -t docker.pkg.github.com/soerensofke/diamonddust/riscv-gnu-toolchain-rv32i:latest ./.github/workflows/riscv-gnu-toolchain-rv32i
        docker push docker.pkg.github.com/soerensofke/diamonddust/riscv-gnu-toolchain-rv32i:latest      
      env:
          PACKAGE_TOKEN: ${{ secrets.PACKAGE_TOKEN }}
