name: Docker Image Verilog

on:
  push:
    paths:
    - '**verilog/Dockerfile'
    - '**verilog.yml'

jobs:

  build:
 
    runs-on: ubuntu-18.04
 
    steps:
    - uses: actions/checkout@v1
    - name: Docker Image Verilog
      run: |
        echo $PACKAGE_TOKEN | docker login docker.pkg.github.com --username soerensofke --password-stdin
        docker build -t docker.pkg.github.com/soerensofke/diamonddust/verilog:latest ./.github/workflows/verilog 
        docker push docker.pkg.github.com/soerensofke/diamonddust/verilog:latest     
      env:
          PACKAGE_TOKEN: ${{ secrets.PACKAGE_TOKEN }}
