name: Docker Image Verilog

on:
  push:
    paths:
    - '**verilog/Dockerfile'
    - '**verilog.yml'

jobs:

  build:
 
    runs-on: ubuntu-18.04
 
    steps:
    - uses: actions/checkout@v1
    - name: Docker Image Verilog
      run: |
        echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin
        docker build -t soerensofke/diamonddust:verilog ./.github/workflows/verilog 
        docker push soerensofke/diamonddust:verilog        
      env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
